import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import {
  Users, FileText, FileSpreadsheet, FileBarChart,
  Download, RefreshCw, Filter, Calendar, Search,
  ChevronDown, ChevronUp, Eye, Printer, CheckCircle,
  AlertCircle, Loader2, Database, BarChart3, PieChart,
  TrendingUp, Clock, Target, AlertOctagon, Shield,
  UserCheck, Activity, DollarSign, Layers,
  ArrowUpRight, ArrowDownRight, Percent, Trash2,
  Edit, ExternalLink, MoreVertical, X, Plus,
  Grid, List, Settings, ChevronRight, FileDown,
  DownloadCloud, Upload, CheckSquare, ClipboardList,
  CalendarCheck, UserCog, Bell, Building, Award,
  Briefcase, GraduationCap, BookOpen, MessageCircle
} from 'lucide-react';

// Import client-side export libraries
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
// Import the plugin properly
import autoTable from 'jspdf-autotable';

// Add autoTable to jsPDF prototype
jsPDF.autoTable = autoTable;

// Role-based API Service
const apiService = {
  async generateReport(reportType, filters, userRole) {
    const accessToken = localStorage.getItem('access_token');

    // Role-based endpoint mapping
    const endpointMap = {
      // Admin endpoints
      admin: {
        users: 'admin/users/analytics/',
        tasks: 'admin/performance/',
        assignments: 'admin/shifts/',
        performance: 'admin/performance/',
        dashboard: 'admin/dashboard/',
        shifts: 'admin/shifts/'
      },
      // Supervisor endpoints
      supervisor: {
        attendance: 'supervisor/attendance/',
        team_performance: 'supervisor/team/performance/',
        team_summary: 'supervisor/dashboard/'
      }
    };

    // Get appropriate endpoint based on user role
    let endpoint;
    if (userRole === 'admin') {
      endpoint = endpointMap.admin[reportType];
    } else if (userRole === 'supervisor') {
      endpoint = endpointMap.supervisor[reportType];
    }

    if (!endpoint) {
      throw new Error(`Report type "${reportType}" not available for your role (${userRole})`);
    }

    const params = new URLSearchParams();
    if (filters.days) params.append('days', filters.days);
    if (filters.date) params.append('date', filters.date);
    if (filters.status) params.append('status', filters.status);
    if (filters.role) params.append('role', filters.role);

    const url = `http://127.0.0.1:8000/report/${endpoint}?${params.toString()}`;

    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      }
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ message: 'Unknown error' }));
      throw new Error(`API Error ${response.status}: ${errorData.message || response.statusText}`);
    }

    return await response.json();
  }
};

// Export Service (Client-side)
const exportService = {
  // Generate PDF with professional styling
  async generatePDF(reportData, config = {}, tablesFromUI = []) {
    const { summary, detailed_data, metadata, report_type } = reportData;
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // Add header with logo and title
    doc.setFillColor(41, 128, 185); // Blue header
    doc.rect(0, 0, pageWidth, 30, 'F');

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('CCI-Rwanda', pageWidth / 2, 12, { align: 'center' });

    // Subtitle
    doc.setFontSize(14);
    doc.text('Time Sync: AI-Powered Real-Time Employee Monitoring System', pageWidth / 2, 20, { align: 'center' });

    // Confidential Header
    doc.setFillColor(255, 0, 0); // Red
    doc.rect(0, 30, pageWidth, 10, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('CONFIDENTIAL REPORT', pageWidth / 2, 36, { align: 'center' });

    let yPos = 50;

    // Report Title
    doc.setFillColor(245, 245, 245);
    doc.rect(10, yPos, pageWidth - 20, 15, 'F');
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(`${this.getReportTitle(report_type)} Report`, pageWidth / 2, yPos + 10, { align: 'center' });
    yPos += 25;

    // Report Info Table
    const reportInfo = [
      ['Generated on:', new Date().toLocaleString()],
      ['Generated by:', config.generated_by || metadata?.generated_by || 'System'],
      ['Report Type:', this.getReportTitle(report_type)],
      ['Total Records:', this.getTotalRecords(reportData) || 'N/A']
    ];

    doc.autoTable({
      startY: yPos,
      head: [['Report Information', 'Details']],
      body: reportInfo,
      theme: 'grid',
      headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
      styles: { fontSize: 10, cellPadding: 3 },
      margin: { left: 20, right: 20 }
    });

    yPos = doc.lastAutoTable.finalY + 15;

    // Key Metrics Section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Key Metrics', 20, yPos);
    yPos += 10;

    // Generate metrics table based on report type
    const metrics = this.getMetricsForReport(reportData);
    if (metrics.length > 0) {
      doc.autoTable({
        startY: yPos,
        head: [['Metric', 'Value']],
        body: metrics,
        theme: 'grid',
        headStyles: { fillColor: [52, 152, 219], textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 4 },
        margin: { left: 20, right: 20 }
      });
      yPos = doc.lastAutoTable.finalY + 15;
    }

    // Detailed Data Section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Detailed Data', 20, yPos);
    yPos += 10;

    // Generate detailed tables based on report type
    const detailedTables = tablesFromUI.length > 0 ? tablesFromUI : this.getDetailedTables(reportData);

    for (const tableData of detailedTables) {
      if (tableData.data && tableData.data.length > 0) {
        // Add page break if needed
        if (yPos > doc.internal.pageSize.height - 50) {
          doc.addPage();
          yPos = 20;
        }

        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text(tableData.title, 20, yPos);
        yPos += 8;

        // Limit to first 100 records for PDF (can be adjusted)
        const displayData = tableData.data.slice(0, 100);

        doc.autoTable({
          startY: yPos,
          head: [tableData.headers],
          body: displayData,
          theme: 'grid',
          headStyles: { fillColor: [88, 214, 141], textColor: 255, fontStyle: 'bold' },
          styles: { fontSize: 8, cellPadding: 2 },
          margin: { left: 15, right: 15 },
          pageBreak: 'auto'
        });

        yPos = doc.lastAutoTable.finalY + 15;

        if (tableData.data.length > 100) {
          doc.setFontSize(8);
          doc.setFont('helvetica', 'italic');
          doc.text(`Showing 100 of ${tableData.data.length} records. Full data available in Excel export.`, 20, yPos);
          yPos += 10;
        }
      }
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(100, 100, 100);
      doc.text('Confidential Information - CCI-Rwanda', pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
      doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.height - 5, { align: 'center' });
    }

    return doc.output('blob');
  },

  // Generate Excel file with all displayed data
  async generateExcel(reportData, config = {}, tablesFromUI = []) {
    const { summary, detailed_data, metadata, report_type } = reportData;
    const wb = XLSX.utils.book_new();

    // Sheet 1: Report Summary
    const summaryData = [
      ['CCI-Rwanda'],
      ['Time Sync: AI-Powered Real-Time Employee Monitoring System'],
      ['CONFIDENTIAL REPORT'],
      [],
      [`${this.getReportTitle(report_type)} Report`],
      [],
      ['Report Information'],
      ['Generated on:', new Date().toLocaleString()],
      ['Generated by:', config.generated_by || metadata?.generated_by || 'System'],
      ['Report Type:', this.getReportTitle(report_type)],
      ['Total Records:', this.getTotalRecords(reportData) || 'N/A'],
      [],
      ['Key Metrics']
    ];

    // Add metrics
    const metrics = this.getMetricsForReport(reportData);
    summaryData.push(['Metric', 'Value']);
    metrics.forEach(metric => summaryData.push(metric));

    const ws1 = XLSX.utils.aoa_to_sheet(summaryData);

    // Apply styling
    const ws1Range = XLSX.utils.decode_range(ws1['!ref']);
    for (let R = ws1Range.s.r; R <= ws1Range.s.r + 2; R++) {
      for (let C = ws1Range.s.c; C <= ws1Range.e.c; C++) {
        const cellAddress = XLSX.utils.encode_cell({ r: R, c: C });
        if (!ws1[cellAddress]) continue;
        ws1[cellAddress].s = { font: { bold: true }, alignment: { horizontal: 'center' } };
      }
    }

    XLSX.utils.book_append_sheet(wb, ws1, 'Report Summary');

    // Add detailed data sheets
    const detailedTables = tablesFromUI.length > 0 ? tablesFromUI : this.getDetailedTables(reportData);

    detailedTables.forEach((tableData, index) => {
      if (tableData.data && tableData.data.length > 0) {
        const sheetData = [tableData.headers, ...tableData.data];
        const ws = XLSX.utils.aoa_to_sheet(sheetData);

        // Style header row
        const range = XLSX.utils.decode_range(ws['!ref']);
        for (let C = range.s.c; C <= range.e.c; C++) {
          const cellAddress = XLSX.utils.encode_cell({ r: 0, c: C });
          ws[cellAddress].s = {
            font: { bold: true, color: { rgb: "FFFFFF" } },
            fill: { fgColor: { rgb: "2980B9" } },
            alignment: { horizontal: 'center' }
          };
        }

        // Add alternating row colors
        for (let R = 1; R <= range.e.r; R++) {
          for (let C = range.s.c; C <= range.e.c; C++) {
            const cellAddress = XLSX.utils.encode_cell({ r: R, c: C });
            if (ws[cellAddress]) {
              ws[cellAddress].s = {
                ...ws[cellAddress].s,
                fill: {
                  fgColor: {
                    rgb: R % 2 === 0 ? "F8F9FA" : "FFFFFF"
                  }
                }
              };
            }
          }
        }

        // Auto-size columns
        const maxWidths = {};
        for (let R = 0; R <= range.e.r; R++) {
          for (let C = range.s.c; C <= range.e.c; C++) {
            const cellAddress = XLSX.utils.encode_cell({ r: R, c: C });
            const cell = ws[cellAddress];
            if (cell && cell.v) {
              const cellValue = String(cell.v);
              maxWidths[C] = Math.max(maxWidths[C] || 0, Math.min(cellValue.length, 50));
            }
          }
        }

        ws['!cols'] = Object.keys(maxWidths).map(key => ({
          wch: maxWidths[key] + 2
        }));

        const sheetName = tableData.title.length > 31
          ? `${tableData.title.substring(0, 28)}...`
          : tableData.title;
        XLSX.utils.book_append_sheet(wb, ws, sheetName);
      }
    });

    // Generate Excel file
    const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
    return new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  },

  // Generate CSV file with all displayed data
  async generateCSV(reportData, config = {}, tablesFromUI = []) {
    const { summary, detailed_data, metadata, report_type } = reportData;
    let csvContent = '';

    // Header
    csvContent += 'CCI-Rwanda\n';
    csvContent += 'Time Sync: AI-Powered Real-Time Employee Monitoring System\n';
    csvContent += 'CONFIDENTIAL REPORT\n\n';
    csvContent += `${this.getReportTitle(report_type)} Report\n\n`;

    // Report Info
    csvContent += 'Report Information\n';
    csvContent += `Generated on:,${new Date().toLocaleString()}\n`;
    csvContent += `Generated by:,${config.generated_by || metadata?.generated_by || 'System'}\n`;
    csvContent += `Report Type:,${this.getReportTitle(report_type)}\n`;
    csvContent += `Total Records:,${this.getTotalRecords(reportData) || 'N/A'}\n\n`;

    // Key Metrics
    csvContent += 'Key Metrics\n';
    const metrics = this.getMetricsForReport(reportData);
    csvContent += 'Metric,Value\n';
    metrics.forEach(metric => {
      csvContent += `${metric[0]},${metric[1]}\n`;
    });

    // Detailed Data
    const detailedTables = tablesFromUI.length > 0 ? tablesFromUI : this.getDetailedTables(reportData);

    detailedTables.forEach((tableData, index) => {
      if (tableData.data && tableData.data.length > 0) {
        csvContent += `\n\n${tableData.title}\n`;
        csvContent += tableData.headers.join(',') + '\n';
        tableData.data.forEach(row => {
          const escapedRow = row.map(cell => {
            const cellStr = String(cell);
            if (cellStr.includes(',') || cellStr.includes('"') || cellStr.includes('\n')) {
              return `"${cellStr.replace(/"/g, '""')}"`;
            }
            return cellStr;
          });
          csvContent += escapedRow.join(',') + '\n';
        });
      }
    });

    return new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  },

  // Helper methods
  getReportTitle(reportType) {
    const titles = {
      users: 'User Registration',
      tasks: 'Task Performance',
      assignments: 'Shift Assignments',
      performance: 'Performance',
      attendance: 'Attendance',
      shifts: 'Shift Management'
    };
    return titles[reportType] || reportType.charAt(0).toUpperCase() + reportType.slice(1);
  },

  getTotalRecords(reportData) {
    const { summary, detailed_data, metadata } = reportData;

    if (metadata?.total_records) {
      const totals = Object.values(metadata.total_records);
      return totals.reduce((a, b) => a + b, 0);
    }

    if (detailed_data) {
      const dataArrays = Object.values(detailed_data).filter(Array.isArray);
      return dataArrays.reduce((total, arr) => total + arr.length, 0);
    }

    return 0;
  },

  getMetricsForReport(reportData) {
    const { summary, report_type } = reportData;
    const metrics = [];

    switch (report_type) {
      case 'users':
        metrics.push(
          ['Total Users', summary.total_users || 0],
          ['Active Today', summary.active_today || 0],
          ['Recent Registrations', summary.recent_registrations || 0],
          ['Average Salary', `FRW ${summary.average_salary?.toFixed(2) || '0.00'}`]
        );
        break;

      case 'tasks':
      case 'performance':
        if (summary.task_performance) {
          metrics.push(
            ['Total Tasks', summary.task_performance.total || 0],
            ['Completed Tasks', summary.task_performance.completed || 0],
            ['In Progress', summary.task_performance.in_progress || 0],
            ['Completion Rate', `${summary.task_performance.completion_rate || 0}%`]
          );
        }
        break;

      case 'attendance':
        if (summary.attendance_summary) {
          metrics.push(
            ['Total Employees', summary.attendance_summary.total_users || summary.attendance_details?.length || 0],
            ['Present', summary.attendance_summary.present || 0],
            ['Absent', summary.attendance_summary.absent || 0],
            ['Attendance Rate', `${summary.attendance_summary.attendance_rate || 0}%`]
          );
        }
        break;

      case 'assignments':
      case 'shifts':
        metrics.push(
          ['Total Shifts', summary.total_shifts || 0],
          ['Active Shifts', summary.active_shifts || 0],
          ['Inactive Shifts', summary.inactive_shifts || 0],
          ['Average Users/Shift', summary.average_users_per_shift?.toFixed(2) || '0']
        );
        break;
    }

    return metrics;
  },

  getDetailedTables(reportData) {
    const { detailed_data, report_type } = reportData;
    const tables = [];

    // If no detailed_data, try to extract from summary
    if (!detailed_data && reportData.summary) {
      // Try to extract tables from summary for attendance
      if (report_type === 'attendance' && reportData.summary.attendance_details) {
        tables.push({
          title: 'Attendance Details',
          headers: ['Employee Name', 'Employee Number', 'Shift', 'Status', 'Login Time', 'Logout Time', 'Hours Worked'],
          data: reportData.summary.attendance_details.map(attendance => [
            attendance.employee_name,
            attendance.employee_number,
            attendance.shift,
            attendance.status,
            attendance.first_login_time ? new Date(attendance.first_login_time).toLocaleString() : 'N/A',
            attendance.last_logout_time ? new Date(attendance.last_logout_time).toLocaleString() : 'N/A',
            attendance.hours_worked !== null ? `${attendance.hours_worked.toFixed(2)} hours` : 'N/A'
          ])
        });
      }
      return tables;
    }

    switch (report_type) {
      case 'users':
        if (detailed_data.all_users && detailed_data.all_users.length > 0) {
          tables.push({
            title: 'Users List',
            headers: ['Name', 'Employee Number', 'Email', 'Role', 'Status', 'Shift', 'Gender', 'Created At'],
            data: detailed_data.all_users.map(user => [
              user.names,
              user.emp_number,
              user.email,
              user.role,
              user.status,
              user.current_shift__name || 'N/A',
              user.gender || 'N/A',
              user.created_at ? new Date(user.created_at).toLocaleDateString() : 'N/A'
            ])
          });
        }
        if (detailed_data.users_by_shift_detailed && detailed_data.users_by_shift_detailed.length > 0) {
          tables.push({
            title: 'Users by Shift',
            headers: ['Shift Name', 'Total Users', 'Active Users', 'Activity Rate'],
            data: detailed_data.users_by_shift_detailed.map(shift => {
              const activityRate = shift.user_count > 0
                ? Math.round((shift.active_users / shift.user_count) * 100)
                : 0;
              return [
                shift.name,
                shift.user_count,
                shift.active_users || 0,
                `${activityRate}%`
              ];
            })
          });
        }
        break;

      case 'tasks':
      case 'performance':
        if (detailed_data.break_logs && detailed_data.break_logs.length > 0) {
          tables.push({
            title: 'Break Performance',
            headers: ['Employee', 'Break Type', 'Scheduled Start', 'Actual Start', 'Status', 'Punctuality'],
            data: detailed_data.break_logs.map(log => [
              log.user__names,
              log.break_template__name,
              new Date(log.scheduled_start).toLocaleString(),
              log.actual_start ? new Date(log.actual_start).toLocaleString() : 'N/A',
              log.status,
              log.start_punctuality || 'N/A'
            ])
          });
        }
        if (detailed_data.task_assignments && detailed_data.task_assignments.length > 0) {
          tables.push({
            title: 'Task Assignments',
            headers: ['Employee', 'Task', 'Assignment Date', 'Start Time', 'End Time', 'Status', 'Priority'],
            data: detailed_data.task_assignments.map(task => [
              task.user__names,
              task.task__name,
              task.assignment_date,
              new Date(task.start_time).toLocaleTimeString(),
              new Date(task.end_time).toLocaleTimeString(),
              task.status,
              task.priority
            ])
          });
        }
        break;

      case 'attendance':
        if (detailed_data.attendance_details && detailed_data.attendance_details.length > 0) {
          tables.push({
            title: 'Attendance Details',
            headers: ['Employee Name', 'Employee Number', 'Shift', 'Status', 'Login Time', 'Logout Time', 'Hours Worked'],
            data: detailed_data.attendance_details.map(attendance => [
              attendance.employee_name,
              attendance.employee_number,
              attendance.shift,
              attendance.status,
              attendance.first_login_time ? new Date(attendance.first_login_time).toLocaleString() : 'N/A',
              attendance.last_logout_time ? new Date(attendance.last_logout_time).toLocaleString() : 'N/A',
              attendance.hours_worked !== null ? `${attendance.hours_worked.toFixed(2)} hours` : 'N/A'
            ])
          });
        }
        break;

      case 'assignments':
      case 'shifts':
        if (detailed_data.shifts && detailed_data.shifts.length > 0) {
          tables.push({
            title: 'Shifts',
            headers: ['Shift Name', 'Start Time', 'End Time', 'Status', 'Description'],
            data: detailed_data.shifts.map(shift => [
              shift.name,
              shift.start_at,
              shift.end_at,
              shift.status,
              shift.description || 'N/A'
            ])
          });
        }
        if (detailed_data.break_templates && detailed_data.break_templates.length > 0) {
          tables.push({
            title: 'Break Templates',
            headers: ['Break Name', 'Shift', 'Start Time', 'End Time', 'Status'],
            data: detailed_data.break_templates.map(template => [
              template.name,
              template.shift__name,
              template.start_at,
              template.end_at,
              template.status
            ])
          });
        }
        break;
    }

    return tables;
  }
};

// Custom Components
const LoadingSpinner = ({ text = 'Loading...', size = 'md' }) => {
  const sizeClasses = {
    sm: 'w-4 h-4',
    md: 'w-8 h-8',
    lg: 'w-12 h-12'
  };

  return (
    <div className="flex flex-col items-center justify-center p-8">
      <Loader2 className={`${sizeClasses[size]} text-blue-600 animate-spin mb-3`} />
      <span className="text-gray-600 font-medium">{text}</span>
    </div>
  );
};

const ErrorMessage = ({ message, onRetry }) => (
  <div className="bg-gradient-to-br from-red-50 to-rose-50 border border-red-200 rounded-xl p-6 text-center shadow-sm">
    <div className="w-16 h-16 bg-gradient-to-br from-red-100 to-rose-100 rounded-full flex items-center justify-center mx-auto mb-4">
      <AlertCircle className="w-8 h-8 text-red-600" />
    </div>
    <h3 className="text-lg font-semibold text-red-800 mb-2">Unable to Process</h3>
    <p className="text-red-600 mb-5">{message}</p>
    {onRetry && (
      <button
        onClick={onRetry}
        className="px-5 py-2.5 bg-gradient-to-r from-red-600 to-rose-600 text-white rounded-lg hover:from-red-700 hover:to-rose-700 transition-all duration-300 font-medium shadow-md hover:shadow-lg"
      >
        <RefreshCw className="w-4 h-4 inline mr-2" />
        Try Again
      </button>
    )}
  </div>
);

const SuccessMessage = ({ message }) => (
  <div className="bg-gradient-to-br from-green-50 to-emerald-50 border border-green-200 rounded-xl p-5">
    <div className="flex items-center">
      <CheckCircle className="w-5 h-5 text-green-600 mr-3" />
      <span className="text-green-800 font-medium">{message}</span>
    </div>
  </div>
);

const StatCard = ({ title, value, icon: Icon, color, change, description }) => {
  const colorClasses = {
    blue: { bg: 'from-blue-500 to-blue-600', light: 'bg-blue-50', text: 'text-blue-600' },
    green: { bg: 'from-emerald-500 to-emerald-600', light: 'bg-emerald-50', text: 'text-emerald-600' },
    purple: { bg: 'from-violet-500 to-violet-600', light: 'bg-violet-50', text: 'text-violet-600' },
    orange: { bg: 'from-orange-500 to-orange-600', light: 'bg-orange-50', text: 'text-orange-600' },
    red: { bg: 'from-rose-500 to-rose-600', light: 'bg-rose-50', text: 'text-rose-600' }
  };

  const { bg, light, text } = colorClasses[color] || colorClasses.blue;
  const isPositive = change > 0;
  const TrendIcon = isPositive ? ArrowUpRight : ArrowDownRight;

  return (
    <div className="bg-white rounded-xl border border-gray-200 p-5 hover:shadow-md transition-shadow">
      <div className="flex items-start justify-between mb-4">
        <div className={`p-3 rounded-lg ${light}`}>
          <Icon className={`w-6 h-6 ${text}`} />
        </div>
        {change !== undefined && (
          <div className={`flex items-center gap-1 px-2 py-1 rounded-full text-xs font-semibold ${isPositive ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>
            <TrendIcon className="w-3 h-3" />
            <span>{Math.abs(change)}%</span>
          </div>
        )}
      </div>
      <div>
        <p className="text-sm font-medium text-gray-500 mb-1">{title}</p>
        <h3 className="text-2xl font-bold text-gray-900 mb-2">{value}</h3>
        {description && (
          <p className="text-xs text-gray-500">{description}</p>
        )}
      </div>
    </div>
  );
};

const ReportTypeCard = ({ title, description, icon: Icon, onSelect, isActive }) => (
  <button
    onClick={onSelect}
    className={`relative group bg-white rounded-xl border ${isActive ? 'border-blue-500 ring-2 ring-blue-100 bg-blue-50/50' : 'border-gray-200 hover:border-blue-300 hover:bg-blue-50/30'} p-5 text-left transition-all duration-300`}
  >
    <div className="flex items-start space-x-4">
      <div className={`p-3 rounded-xl ${isActive ? 'bg-blue-100' : 'bg-gray-100 group-hover:bg-blue-100'} transition-colors`}>
        <Icon className={`w-6 h-6 ${isActive ? 'text-blue-600' : 'text-gray-600 group-hover:text-blue-600'}`} />
      </div>
      <div className="flex-1">
        <h4 className={`font-semibold ${isActive ? 'text-blue-700' : 'text-gray-900'} mb-1`}>{title}</h4>
        <p className="text-sm text-gray-600">{description}</p>
      </div>
      <ChevronRight className={`w-5 h-5 ${isActive ? 'text-blue-500' : 'text-gray-400'}`} />
    </div>
  </button>
);

// Data Table Component
const DataTable = ({ title, headers, data, showCount = true }) => {
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);
  const [sortConfig, setSortConfig] = useState({ key: null, direction: 'asc' });

  const handleSort = (key) => {
    let direction = 'asc';
    if (sortConfig.key === key && sortConfig.direction === 'asc') {
      direction = 'desc';
    }
    setSortConfig({ key, direction });
  };

  // Update the sortedData memo to handle array data correctly:
  const sortedData = React.useMemo(() => {
    if (!sortConfig.key || !data || data.length === 0) return data;

    return [...data].sort((a, b) => {
      // For array data (like table rows), a and b are arrays
      if (Array.isArray(a) && Array.isArray(b)) {
        const aValue = a[sortConfig.key];
        const bValue = b[sortConfig.key];

        // Handle different data types
        if (typeof aValue === 'string' && typeof bValue === 'string') {
          return sortConfig.direction === 'asc'
            ? aValue.localeCompare(bValue)
            : bValue.localeCompare(aValue);
        }

        // Handle numbers
        if (!isNaN(aValue) && !isNaN(bValue)) {
          return sortConfig.direction === 'asc'
            ? parseFloat(aValue) - parseFloat(bValue)
            : parseFloat(bValue) - parseFloat(aValue);
        }

        // Default comparison
        if (aValue < bValue) return sortConfig.direction === 'asc' ? -1 : 1;
        if (aValue > bValue) return sortConfig.direction === 'asc' ? 1 : -1;
        return 0;
      }

      return 0;
    });
  }, [data, sortConfig]);

  const totalPages = Math.ceil((sortedData?.length || 0) / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const paginatedData = sortedData?.slice(startIndex, startIndex + itemsPerPage) || [];

  return (
    <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
      <div className="px-6 py-4 border-b border-gray-200 bg-gray-50">
        <div className="flex items-center justify-between">
          <div>
            <h4 className="font-semibold text-gray-900">{title}</h4>
            {showCount && data && (
              <p className="text-sm text-gray-600">{data.length} records</p>
            )}
          </div>
          {data && data.length > 0 && (
            <div className="flex items-center space-x-4">
              <div className="flex items-center">
                <span className="text-sm text-gray-600 mr-2">Show:</span>
                <select
                  value={itemsPerPage}
                  onChange={(e) => {
                    setItemsPerPage(Number(e.target.value));
                    setCurrentPage(1);
                  }}
                  className="border border-gray-300 rounded-lg px-3 py-1 text-sm"
                >
                  <option value="10">10</option>
                  <option value="25">25</option>
                  <option value="50">50</option>
                  <option value="100">100</option>
                </select>
              </div>
            </div>
          )}
        </div>
      </div>

      {data && data.length > 0 ? (
        <>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-100">
                <tr>
                  {headers.map((header, index) => (
                    <th
                      key={index}
                      className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider cursor-pointer hover:bg-gray-200"
                      onClick={() => handleSort(index)}
                    >
                      <div className="flex items-center">
                        {header}
                        {sortConfig.key === index && (
                          <ChevronUp className={`w-4 h-4 ml-1 ${sortConfig.direction === 'desc' ? 'transform rotate-180' : ''}`} />
                        )}
                      </div>
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {paginatedData.map((row, rowIndex) => (
                  <tr key={rowIndex} className="hover:bg-gray-50 transition-colors">
                    {row.map((cell, cellIndex) => (
                      <td key={cellIndex} className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                        {cell || 'N/A'}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {totalPages > 1 && (
            <div className="px-6 py-4 border-t border-gray-200 bg-gray-50">
              <div className="flex items-center justify-between">
                <div className="text-sm text-gray-700">
                  Showing {startIndex + 1} to {Math.min(startIndex + itemsPerPage, data.length)} of {data.length} entries
                </div>
                <div className="flex space-x-2">
                  <button
                    onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
                    disabled={currentPage === 1}
                    className="px-3 py-1 border border-gray-300 rounded-lg text-sm disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Previous
                  </button>
                  <div className="flex items-center space-x-1">
                    {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
                      let pageNum;
                      if (totalPages <= 5) {
                        pageNum = i + 1;
                      } else if (currentPage <= 3) {
                        pageNum = i + 1;
                      } else if (currentPage >= totalPages - 2) {
                        pageNum = totalPages - 4 + i;
                      } else {
                        pageNum = currentPage - 2 + i;
                      }
                      return (
                        <button
                          key={pageNum}
                          onClick={() => setCurrentPage(pageNum)}
                          className={`px-3 py-1 rounded-lg text-sm ${currentPage === pageNum ? 'bg-blue-600 text-white' : 'border border-gray-300'}`}
                        >
                          {pageNum}
                        </button>
                      );
                    })}
                  </div>
                  <button
                    onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
                    disabled={currentPage === totalPages}
                    className="px-3 py-1 border border-gray-300 rounded-lg text-sm disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Next
                  </button>
                </div>
              </div>
            </div>
          )}
        </>
      ) : (
        <div className="p-12 text-center">
          <div className="w-20 h-20 bg-gradient-to-br from-gray-100 to-gray-200 rounded-full flex items-center justify-center mx-auto mb-6">
            <Database className="w-10 h-10 text-gray-400" />
          </div>
          <h3 className="text-lg font-semibold text-gray-900 mb-2">No Data Available</h3>
          <p className="text-gray-600">No records found for this report</p>
        </div>
      )}
    </div>
  );
};


const calculateAveragePerformance = (summary, type) => {
  if (!summary.team_performance || !Array.isArray(summary.team_performance)) {
    return 0;
  }

  const teamPerf = summary.team_performance;

  switch (type) {
    case 'task':
      const taskRates = teamPerf.map(emp =>
        emp.task_performance?.completion_rate || 0
      );
      return taskRates.length > 0
        ? Math.round(taskRates.reduce((a, b) => a + b, 0) / taskRates.length)
        : 0;

    case 'break':
      const breakRates = teamPerf.map(emp =>
        emp.break_performance?.completion_rate || 0
      );
      return breakRates.length > 0
        ? Math.round(breakRates.reduce((a, b) => a + b, 0) / breakRates.length)
        : 0;

    case 'overall':
      const overallRates = teamPerf.map(emp => {
        const taskRate = emp.task_performance?.completion_rate || 0;
        const breakRate = emp.break_performance?.completion_rate || 0;
        return (taskRate + breakRate) / 2;
      });
      return overallRates.length > 0
        ? Math.round(overallRates.reduce((a, b) => a + b, 0) / overallRates.length)
        : 0;

    default:
      return 0;
  }
};

// Main Component - MODIFIED FOR SUPERVISORS
export default function SupervisorReports() {
  const { user, logout } = useAuth();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(null);

  // Report State
  const [selectedReport, setSelectedReport] = useState('attendance');
  const [reportData, setReportData] = useState(null);
  const [filters, setFilters] = useState({
    days: '30',
    date: new Date().toISOString().split('T')[0],
    role: '',
    status: '',
    department: ''
  });
  const [isGenerating, setIsGenerating] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [activeTab, setActiveTab] = useState('summary');

  // Role-based report types
  const getReportTypes = () => {
    const userRole = user?.role || 'employee';

    const baseReports = {
      supervisor: [
        {
          id: 'attendance',
          title: 'Team Attendance',
          description: 'Daily attendance and activity tracking for your team',
          icon: CalendarCheck,
          color: 'red'
        },
        {
          id: 'team_performance',
          title: 'Team Performance',
          description: 'Team performance and productivity metrics',
          icon: Activity,
          color: 'orange'
        },
        {
          id: 'team_summary',
          title: 'Team Summary',
          description: 'Overview of your supervised employees',
          icon: Users,
          color: 'blue'
        }
      ],
      admin: [
        {
          id: 'users',
          title: 'Users Analytics',
          description: 'User distribution, demographics, and activity metrics',
          icon: Users,
          color: 'blue'
        },
        {
          id: 'tasks',
          title: 'Task Performance',
          description: 'Task completion rates and performance metrics',
          icon: Target,
          color: 'green'
        },
        {
          id: 'assignments',
          title: 'Shift Assignments',
          description: 'Shift allocation and user distribution',
          icon: ClipboardList,
          color: 'purple'
        },
        {
          id: 'performance',
          title: 'Performance Report',
          description: 'Break performance and compliance metrics',
          icon: Activity,
          color: 'orange'
        },
        {
          id: 'attendance',
          title: 'Attendance Report',
          description: 'Daily attendance and activity tracking',
          icon: CalendarCheck,
          color: 'red'
        }
      ]
    };

    return baseReports[userRole] || baseReports.supervisor;
  };

  const reportTypes = getReportTypes();

  const handleFilterChange = (key, value) => {
    setFilters(prev => ({ ...prev, [key]: value }));
  };

  const handleGenerateReport = async () => {
    setIsGenerating(true);
    setError(null);
    setSuccess(null);

    try {
      console.log('🚀 Starting report generation for supervisor...');
      console.log('👤 User role:', user?.role);
      console.log('📊 Selected report:', selectedReport);

      const data = await apiService.generateReport(selectedReport, filters, user?.role);

      if (data.success) {
        const reportDataWithType = {
          ...data,
          report_type: selectedReport,
          generated_at: new Date().toISOString(),
          filters: filters
        };

        setReportData(reportDataWithType);

        // Log supervisor-specific data
        console.log('👨‍💼 SUPERVISOR REPORT DATA:', {
          summary: data.summary || 'No summary data',
          supervisorName: data.summary?.supervisor_name || user?.names,
          teamMembers: data.summary?.total_team_members || data.summary?.total_employees || 0,
          reportType: selectedReport,
          hasAttendanceDetails: !!data.summary?.attendance_details
        });

        setSuccess('Report generated successfully!');
      } else {
        throw new Error(data.message || 'Report generation failed');
      }
    } catch (err) {
      console.error('Report generation error:', err);
      setError(err.message || 'Failed to generate report');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleExport = async (format) => {
    if (!reportData) {
      setError('Please generate a report first');
      return;
    }

    setIsExporting(true);
    setError(null);

    try {
      const config = {
        generated_by: user?.names || 'Supervisor',
        organization: 'CCI-Rwanda',
        system: 'Time Sync: AI-Powered Real-Time Employee Monitoring System',
        supervisor_name: user?.names,
        role: user?.role
      };

      // Get the current displayed tables from UI
      const displayedTables = getDetailedTables();

      let blob;
      let filename = `CCI_Rwanda_${user?.role}_${selectedReport}_${new Date().toISOString().split('T')[0]}`;

      switch (format) {
        case 'pdf':
          blob = await exportService.generatePDF(reportData, config, displayedTables);
          filename += '.pdf';
          break;
        case 'excel':
          blob = await exportService.generateExcel(reportData, config, displayedTables);
          filename += '.xlsx';
          break;
        case 'csv':
          blob = await exportService.generateCSV(reportData, config, displayedTables);
          filename += '.csv';
          break;
        default:
          throw new Error(`Unsupported format: ${format}`);
      }

      // Create download
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

      setSuccess(`${format.toUpperCase()} report exported successfully!`);
      console.log(`✅ Exported ${filename} (${(blob.size / 1024).toFixed(1)} KB)`);
    } catch (err) {
      console.error('Export error:', err);
      setError(`Failed to export ${format.toUpperCase()}: ${err.message}`);
    } finally {
      setIsExporting(false);
    }
  };

  const getReportSummaryStats = () => {
    if (!reportData?.summary) return [];

    const { summary } = reportData;

    switch (selectedReport) {
      case 'team_summary':
        return [
          {
            label: 'Team Members',
            value: summary.total_team_members || 0,
            icon: Users,
            color: 'blue'
          },
          {
            label: 'Present Today',
            value: summary.today_attendance || 0,
            icon: UserCheck,
            color: 'green',
            change: 2.3
          },
          {
            label: 'Today\'s Tasks',
            value: summary.today_tasks || 0,
            icon: CheckSquare,
            color: 'purple'
          },
          {
            label: 'Attendance Rate',
            value: `${summary.attendance_rate || 0}%`,
            icon: TrendingUp,
            color: 'orange',
            change: 3.1
          }
        ];

      case 'team_performance':
        return [
          {
            label: 'Team Size',
            value: summary.total_employees || 0,
            icon: Users,
            color: 'blue'
          },
          {
            label: 'Avg. Task Completion',
            value: `${calculateAveragePerformance(summary, 'task')}%`,  // Fixed: remove "this."
            icon: Target,
            color: 'green',
            change: 5.2
          },
          {
            label: 'Avg. Break Compliance',
            value: `${calculateAveragePerformance(summary, 'break')}%`,  // Fixed: remove "this."
            icon: CheckCircle,
            color: 'purple'
          },
          {
            label: 'Performance Score',
            value: `${calculateAveragePerformance(summary, 'overall')}%`,  // Fixed: remove "this."
            icon: TrendingUp,
            color: 'orange'
          }
        ];

      case 'attendance':
        const attendanceSummary = summary.attendance_summary || {};
        return [
          {
            label: 'Total Employees',
            value: attendanceSummary.total_users || summary.attendance_details?.length || 0,
            icon: Users,
            color: 'blue'
          },
          {
            label: 'Present',
            value: attendanceSummary.present || 0,
            icon: UserCheck,
            color: 'green',
            change: 2.3
          },
          {
            label: 'Absent',
            value: attendanceSummary.absent || 0,
            icon: UserCog,
            color: 'red',
            change: -1.8
          },
          {
            label: 'Attendance Rate',
            value: `${attendanceSummary.attendance_rate || 0}%`,
            icon: TrendingUp,
            color: 'purple',
            change: 3.1
          }
        ];

      default:
        return [];
    }
  };


  const getDetailedTables = () => {
    if (!reportData?.detailed_data && !reportData?.summary) return [];

    const { detailed_data, summary, report_type } = reportData;

    switch (report_type) {
      case 'attendance':
        const attendanceTables = [];

        // Team attendance details
        if (summary.attendance_details && summary.attendance_details.length > 0) {
          attendanceTables.push({
            title: 'Team Attendance Details',
            headers: ['Employee Name', 'Employee Number', 'Role', 'Shift', 'Status', 'Login Time', 'Logout Time', 'Hours Worked'],
            data: summary.attendance_details.map(attendance => [
              attendance.employee_name || attendance.names || 'N/A',
              attendance.employee_number || attendance.emp_number || 'N/A',
              attendance.role || 'N/A',
              attendance.shift || 'N/A',
              attendance.status || 'N/A',
              attendance.first_login_time ? new Date(attendance.first_login_time).toLocaleString() : 'N/A',
              attendance.last_logout_time ? new Date(attendance.last_logout_time).toLocaleString() : 'N/A',
              attendance.hours_worked !== null ? `${attendance.hours_worked.toFixed(2)} hours` : 'N/A'
            ])
          });
        }

        // Activity logs by type
        if (detailed_data?.logs_by_type) {
          const logsByType = detailed_data.logs_by_type;
          const logTypes = ['login', 'logout', 'break_start', 'break_end'];

          logTypes.forEach(logType => {
            if (logsByType[logType] && logsByType[logType].length > 0) {
              attendanceTables.push({
                title: `${logType.replace('_', ' ').toUpperCase()} Logs`,
                headers: ['Employee', 'Time', 'Status', 'Activity', 'Device Info'],
                data: logsByType[logType].map(log => [
                  log.user__names,
                  new Date(log.actual_time).toLocaleString(),
                  log.status,
                  log.activity,
                  log.device_info || 'N/A'
                ])
              });
            }
          });
        }

        return attendanceTables;

      case 'team_performance':
        const performanceTables = [];

        // Team performance summary
        if (summary.team_performance && summary.team_performance.length > 0) {
          performanceTables.push({
            title: 'Team Performance Summary',
            headers: ['Employee', 'Task Completion', 'Break Compliance', 'Attendance', 'Overall Score'],
            data: summary.team_performance.map(emp => [
              emp.employee_name,
              `${emp.task_performance?.completion_rate || 0}%`,
              `${emp.break_performance?.completion_rate || 0}%`,
              `${emp.attendance?.attendance_rate || 0}%`,
              `${Math.round(
                ((emp.task_performance?.completion_rate || 0) +
                  (emp.break_performance?.completion_rate || 0) +
                  (emp.attendance?.attendance_rate || 0)) / 3
              )}%`
            ])
          });
        }

        // Individual break logs
        if (detailed_data?.break_logs && detailed_data.break_logs.length > 0) {
          performanceTables.push({
            title: 'Break Performance Details',
            headers: ['Employee', 'Break Type', 'Scheduled Start', 'Actual Start', 'Status', 'Punctuality'],
            data: detailed_data.break_logs.map(log => [
              log.user__names,
              log.break_template__name,
              new Date(log.scheduled_start).toLocaleString(),
              log.actual_start ? new Date(log.actual_start).toLocaleString() : 'N/A',
              log.status,
              log.start_punctuality || 'N/A'
            ])
          });
        }

        // Individual task assignments
        if (detailed_data?.task_assignments && detailed_data.task_assignments.length > 0) {
          performanceTables.push({
            title: 'Task Assignment Details',
            headers: ['Employee', 'Task', 'Assignment Date', 'Status', 'Priority'],
            data: detailed_data.task_assignments.map(task => [
              task.user__names,
              task.task__name,
              task.assignment_date,
              task.status,
              task.priority
            ])
          });
        }

        return performanceTables;

      case 'team_summary':
        const summaryTables = [];

        // Team members list
        if (detailed_data?.team_members && detailed_data.team_members.length > 0) {
          summaryTables.push({
            title: 'Team Members',
            headers: ['Name', 'Employee Number', 'Email', 'Shift', 'Status'],
            data: detailed_data.team_members.map(member => [
              member.names,
              member.emp_number,
              member.email,
              member.current_shift__name || 'N/A',
              member.status
            ])
          });
        }

        // Today's attendance
        if (detailed_data?.today_attendance_details && detailed_data.today_attendance_details.length > 0) {
          summaryTables.push({
            title: "Today's Attendance",
            headers: ['Employee', 'Login Time', 'Activity'],
            data: detailed_data.today_attendance_details.map(attendance => [
              attendance.user__names,
              new Date(attendance.actual_time).toLocaleString(),
              attendance.activity
            ])
          });
        }

        // Pending requests
        if (detailed_data?.pending_requests_details && detailed_data.pending_requests_details.length > 0) {
          summaryTables.push({
            title: 'Pending Shift Change Requests',
            headers: ['Employee', 'Request Type', 'Reason', 'Submitted'],
            data: detailed_data.pending_requests_details.map(request => [
              request.user__names,
              request.change_type,
              request.reason,
              new Date(request.created_at).toLocaleDateString()
            ])
          });
        }

        return summaryTables;

      default:
        return [];
    }
  };

  // Role-based page title
  const getPageTitle = () => {
    if (user?.role === 'admin') {
      return 'Advanced Reporting System';
    } else if (user?.role === 'supervisor') {
      return 'Team Management Dashboard';
    }
    return 'Employee Reports';
  };

  // Role-based subtitle
  const getPageSubtitle = () => {
    if (user?.role === 'admin') {
      return 'Generate, analyze, and export comprehensive system reports';
    } else if (user?.role === 'supervisor') {
      return 'Monitor and manage your team performance and attendance';
    }
    return 'View your personal reports and statistics';
  };

  // Filter role dropdown based on user role
  const getRoleOptions = () => {
    if (user?.role === 'admin') {
      return (
        <>
          <option value="">All Roles</option>
          <option value="admin">Admin</option>
          <option value="supervisor">Supervisor</option>
          <option value="employee">Employee</option>
        </>
      );
    } else if (user?.role === 'supervisor') {
      return (
        <>
          <option value="">All Team Members</option>
          <option value="employee">Employees Only</option>
        </>
      );
    }
    return <option value="">All Roles</option>;
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-blue-50/20 to-gray-50">
      {/* Header */}
      <div className="max-w-7xl mx-auto px-6 py-5">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-gradient-to-br from-blue-600 to-blue-700 rounded-xl flex items-center justify-center shadow-lg">
              <FileBarChart className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">{getPageTitle()}</h1>
              <p className="text-sm text-gray-600">
                {getPageSubtitle()}
                {user?.role === 'supervisor' && (
                  <span className="ml-2 text-blue-600 font-medium">
                    👨‍💼 Logged in as Supervisor
                  </span>
                )}
              </p>
            </div>
          </div>

          <div className="hidden md:block text-right">
            <p className="text-xs text-gray-500 uppercase tracking-wider font-medium">Generated By</p>
            <p className="text-sm font-semibold text-gray-900">{user?.names || 'Supervisor'}</p>
            <p className="text-xs text-gray-500 capitalize">{user?.role || 'User'}</p>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-6 py-8 space-y-8">
        {/* Error/Success Messages */}
        {error && <ErrorMessage message={error} onRetry={() => setError(null)} />}
        {success && <SuccessMessage message={success} />}

        {/* Report Type Selection */}
        <div className="bg-white rounded-2xl border border-gray-200 shadow-sm">
          <div className="px-6 py-5 border-b border-gray-100">
            <h2 className="text-xl font-bold text-gray-900">
              {user?.role === 'supervisor' ? 'Select Team Report' : 'Select Report Type'}
            </h2>
            <p className="text-sm text-gray-600 mt-1">
              {user?.role === 'supervisor'
                ? 'Choose the type of report for your team'
                : 'Choose the type of report you want to generate'}
            </p>
          </div>

          <div className="p-6">
            <div className={`grid gap-4 ${reportTypes.length === 3
                ? 'grid-cols-1 md:grid-cols-3'
                : 'grid-cols-1 md:grid-cols-2 lg:grid-cols-5'
              }`}>
              {reportTypes.map((report) => (
                <ReportTypeCard
                  key={report.id}
                  title={report.title}
                  description={report.description}
                  icon={report.icon}
                  onSelect={() => {
                    setSelectedReport(report.id);
                    setReportData(null);
                    setError(null);
                  }}
                  isActive={selectedReport === report.id}
                />
              ))}
            </div>
          </div>
        </div>

        {/* Filters Section */}
        <div className="bg-white rounded-2xl border border-gray-200 shadow-sm">
          <div className="px-6 py-5 border-b border-gray-100">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-lg font-semibold text-gray-900">
                  {user?.role === 'supervisor' ? 'Team Report Configuration' : 'Report Configuration'}
                </h3>
                <p className="text-sm text-gray-600">
                  {user?.role === 'supervisor'
                    ? 'Filter and customize your team report'
                    : 'Customize your report with filters and settings'}
                </p>
              </div>

              <div className="flex items-center gap-3">
                {isGenerating && (
                  <div className="flex items-center text-blue-600 font-medium">
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Generating...
                  </div>
                )}

                <button
                  onClick={handleGenerateReport}
                  disabled={isGenerating}
                  className="px-6 py-3 bg-gradient-to-r from-blue-600 to-blue-700 text-white rounded-xl hover:from-blue-700 hover:to-blue-800 transition-all duration-300 font-semibold shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed flex items-center"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                      Processing...
                    </>
                  ) : (
                    <>
                      <FileBarChart className="w-5 h-5 mr-2" />
                      {user?.role === 'supervisor' ? 'Generate Team Report' : 'Generate Report'}
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>

          <div className="p-6">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <Clock className="w-4 h-4 inline mr-2" />
                  Time Period
                </label>
                <select
                  value={filters.days}
                  onChange={(e) => handleFilterChange('days', e.target.value)}
                  className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white"
                >
                  <option value="1">Last 24 Hours</option>
                  <option value="7">Last 7 Days</option>
                  <option value="30">Last 30 Days</option>
                  <option value="90">Last 90 Days</option>
                  <option value="365">Last Year</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <Shield className="w-4 h-4 inline mr-2" />
                  {user?.role === 'supervisor' ? 'Team Member Filter' : 'Role Filter'}
                </label>
                <select
                  value={filters.role}
                  onChange={(e) => handleFilterChange('role', e.target.value)}
                  className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white"
                >
                  {getRoleOptions()}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <Activity className="w-4 h-4 inline mr-2" />
                  Status Filter
                </label>
                <select
                  value={filters.status}
                  onChange={(e) => handleFilterChange('status', e.target.value)}
                  className="w-full px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white"
                >
                  <option value="">All Status</option>
                  <option value="active">Active</option>
                  <option value="inactive">Inactive</option>
                  <option value="pending">Pending</option>
                </select>
              </div>

            </div>

            {(selectedReport === 'attendance' || user?.role === 'supervisor') && (
              <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  <Calendar className="w-4 h-4 inline mr-2" />
                  Select Date
                </label>
                <input
                  type="date"
                  value={filters.date}
                  onChange={(e) => handleFilterChange('date', e.target.value)}
                  className="w-full max-w-xs px-4 py-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white"
                />
              </div>
            )}
          </div>
        </div>

        {/* Report Results */}
        {reportData && (
          <>
            {/* Supervisor-specific debug info */}
            {user?.role === 'supervisor' && (
              <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 mb-6">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="font-semibold text-blue-800 mb-1">Supervisor Report Info</h4>
                    <p className="text-sm text-blue-700">
                      Report for: <span className="font-medium">{reportData.summary?.supervisor_name || user.names}</span>
                    </p>
                    <p className="text-sm text-blue-700">
                      Team Size: <span className="font-medium">
                        {reportData.summary?.total_team_members ||
                          reportData.summary?.total_employees ||
                          reportData.summary?.attendance_summary?.total_users ||
                          0} members
                      </span>
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="text-xs text-blue-600 uppercase font-medium">Scope</p>
                    <p className="text-sm font-semibold text-blue-800">Supervised Team Only</p>
                  </div>
                </div>
              </div>
            )}

            {/* Summary Stats */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              {getReportSummaryStats().map((stat, index) => (
                <StatCard
                  key={index}
                  title={stat.label}
                  value={stat.value}
                  icon={stat.icon}
                  color={stat.color}
                  change={stat.change}
                  description={stat.description}
                />
              ))}
            </div>

            {/* Report Tabs */}
            <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
              <div className="border-b border-gray-200">
                <div className="px-6 py-4 flex items-center justify-between">
                  <div className="flex space-x-6">
                    <button
                      onClick={() => setActiveTab('summary')}
                      className={`px-4 py-2 font-medium rounded-lg transition-colors ${activeTab === 'summary' ? 'bg-blue-100 text-blue-700' : 'text-gray-600 hover:text-gray-900'}`}
                    >
                      <FileText className="w-4 h-4 inline mr-2" />
                      Summary
                    </button>
                    <button
                      onClick={() => setActiveTab('data')}
                      className={`px-4 py-2 font-medium rounded-lg transition-colors ${activeTab === 'data' ? 'bg-blue-100 text-blue-700' : 'text-gray-600 hover:text-gray-900'}`}
                    >
                      <Database className="w-4 h-4 inline mr-2" />
                      {user?.role === 'supervisor' ? 'Team Data' : 'Data View'}
                    </button>
                    <button
                      onClick={() => setActiveTab('export')}
                      className={`px-4 py-2 font-medium rounded-lg transition-colors ${activeTab === 'export' ? 'bg-blue-100 text-blue-700' : 'text-gray-600 hover:text-gray-900'}`}
                    >
                      <Download className="w-4 h-4 inline mr-2" />
                      Export
                    </button>
                  </div>

                  <div className="flex items-center space-x-3">
                    <button
                      onClick={() => window.print()}
                      className="flex items-center px-4 py-2.5 bg-gray-800 text-white rounded-lg hover:bg-gray-900 transition-colors"
                      title="Print Report"
                    >
                      <Printer className="w-4 h-4 mr-2" />
                      Print
                    </button>

                    <div className="flex space-x-2">
                      <button
                        onClick={() => handleExport('pdf')}
                        disabled={isExporting}
                        className="flex items-center px-4 py-2.5 bg-red-500 hover:bg-red-600 text-white rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        title="Export as PDF"
                      >
                        {isExporting ? (
                          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        ) : (
                          <FileText className="w-4 h-4 mr-2" />
                        )}
                        PDF
                      </button>
                      <button
                        onClick={() => handleExport('excel')}
                        disabled={isExporting}
                        className="flex items-center px-4 py-2.5 bg-green-500 hover:bg-green-600 text-white rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        title="Export as Excel"
                      >
                        {isExporting ? (
                          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        ) : (
                          <FileSpreadsheet className="w-4 h-4 mr-2" />
                        )}
                        Excel
                      </button>
                      <button
                        onClick={() => handleExport('csv')}
                        disabled={isExporting}
                        className="flex items-center px-4 py-2.5 bg-blue-500 hover:bg-blue-600 text-white rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        title="Export as CSV"
                      >
                        {isExporting ? (
                          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        ) : (
                          <FileBarChart className="w-4 h-4 mr-2" />
                        )}
                        CSV
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              <div className="p-6">
                {activeTab === 'summary' && (
                  <div className="space-y-6">
                    <div className="bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-200 rounded-2xl p-6">
                      <div className="flex items-center gap-4 mb-6">
                        <div className="p-3 bg-white rounded-xl shadow-sm">
                          <FileText className="w-8 h-8 text-blue-600" />
                        </div>
                        <div>
                          <h3 className="text-xl font-bold text-gray-900">
                            {user?.role === 'supervisor' ? 'Team Report Summary' : 'Report Summary'}
                          </h3>
                          <p className="text-gray-600 mt-1">
                            {user?.role === 'supervisor'
                              ? `Supervisor: ${reportData.summary?.supervisor_name || user.names}`
                              : `Generated on ${new Date(reportData.generated_at).toLocaleDateString()}`
                            }
                          </p>
                        </div>
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                          <h4 className="font-semibold text-gray-900 mb-3">Report Information</h4>
                          <div className="space-y-3 text-sm">
                            <div className="flex justify-between py-2 border-b border-blue-100">
                              <span className="text-gray-600">Report Type:</span>
                              <span className="font-medium text-gray-900">
                                {selectedReport.charAt(0).toUpperCase() + selectedReport.slice(1)}
                              </span>
                            </div>
                            <div className="flex justify-between py-2 border-b border-blue-100">
                              <span className="text-gray-600">Generated By:</span>
                              <span className="font-medium text-gray-900">
                                {reportData.summary?.supervisor_name || user?.names || 'Supervisor'}
                              </span>
                            </div>
                            <div className="flex justify-between py-2 border-b border-blue-100">
                              <span className="text-gray-600">User Role:</span>
                              <span className="font-medium text-gray-900 capitalize">
                                {user?.role}
                              </span>
                            </div>
                            <div className="flex justify-between py-2 border-b border-blue-100">
                              <span className="text-gray-600">Scope:</span>
                              <span className="font-medium text-gray-900">
                                {user?.role === 'supervisor' ? 'Supervised Team Only' : 'All Users'}
                              </span>
                            </div>
                          </div>
                        </div>

                        <div>
                          <h4 className="font-semibold text-gray-900 mb-3">Key Insights</h4>
                          <div className="space-y-3">
                            {getReportSummaryStats().map((stat, index) => (
                              <div key={index} className="flex items-center justify-between p-3 bg-white rounded-lg shadow-sm">
                                <span className="text-gray-700">{stat.label}</span>
                                <span className="font-bold text-blue-600">{stat.value}</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                {activeTab === 'data' && (
                  <div className="space-y-8">
                    {getDetailedTables().map((table, index) => (
                      <DataTable
                        key={index}
                        title={table.title}
                        headers={table.headers}
                        data={table.data}
                      />
                    ))}
                  </div>
                )}

                {activeTab === 'export' && (
                  <div className="bg-gradient-to-br from-gray-50 to-gray-100 rounded-2xl p-8">
                    <div className="text-center max-w-2xl mx-auto">
                      <div className="w-20 h-20 bg-gradient-to-br from-blue-500 to-blue-600 rounded-full flex items-center justify-center mx-auto mb-6">
                        <DownloadCloud className="w-10 h-10 text-white" />
                      </div>
                      <h3 className="text-2xl font-bold text-gray-900 mb-3">Export Report</h3>
                      <p className="text-gray-600 mb-8">
                        {user?.role === 'supervisor'
                          ? 'Download your team report in multiple formats for analysis, sharing, or archiving.'
                          : 'Download your report in multiple formats for analysis, sharing, or archiving.'
                        }
                        Reports will include both summary and detailed data.
                      </p>

                      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        <div className="bg-white p-6 rounded-xl border border-gray-200 text-center hover:shadow-lg transition-shadow">
                          <div className="w-12 h-12 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
                            <FileText className="w-6 h-6 text-red-600" />
                          </div>
                          <h4 className="font-semibold text-gray-900 mb-2">PDF Format</h4>
                          <p className="text-sm text-gray-600 mb-4">Best for printing and sharing</p>
                          <button
                            onClick={() => handleExport('pdf')}
                            disabled={isExporting}
                            className="w-full py-2.5 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors disabled:opacity-50"
                          >
                            {isExporting ? 'Exporting...' : 'Export PDF'}
                          </button>
                        </div>

                        <div className="bg-white p-6 rounded-xl border border-gray-200 text-center hover:shadow-lg transition-shadow">
                          <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                            <FileSpreadsheet className="w-6 h-6 text-green-600" />
                          </div>
                          <h4 className="font-semibold text-gray-900 mb-2">Excel Format</h4>
                          <p className="text-sm text-gray-600 mb-4">Best for data analysis</p>
                          <button
                            onClick={() => handleExport('excel')}
                            disabled={isExporting}
                            className="w-full py-2.5 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors disabled:opacity-50"
                          >
                            {isExporting ? 'Exporting...' : 'Export Excel'}
                          </button>
                        </div>

                        <div className="bg-white p-6 rounded-xl border border-gray-200 text-center hover:shadow-lg transition-shadow">
                          <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
                            <FileBarChart className="w-6 h-6 text-blue-600" />
                          </div>
                          <h4 className="font-semibold text-gray-900 mb-2">CSV Format</h4>
                          <p className="text-sm text-gray-600 mb-4">Best for data import</p>
                          <button
                            onClick={() => handleExport('csv')}
                            disabled={isExporting}
                            className="w-full py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50"
                          >
                            {isExporting ? 'Exporting...' : 'Export CSV'}
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </>
        )}

        {/* Footer */}
        <div className="bg-gradient-to-br from-gray-900 to-gray-800 rounded-2xl p-6 text-white">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 bg-white/10 rounded-xl flex items-center justify-center backdrop-blur-sm">
                <Shield className="w-6 h-6 text-emerald-400" />
              </div>
              <div>
                <h4 className="font-bold text-lg">
                  {user?.role === 'supervisor' ? 'Team Management Dashboard' : 'Advanced Reporting System'}
                </h4>
                <p className="text-sm text-gray-300">CCI-Rwanda v2.0</p>
              </div>
            </div>
            <div className="text-right">
              <p className="text-xs text-gray-400 uppercase tracking-wider font-medium mb-1">
                {user?.role === 'supervisor' ? 'Team Supervisor' : 'Generated By'}
              </p>
              <p className="text-sm font-semibold">{user?.names || 'Supervisor'}</p>
              <p className="text-xs text-gray-300 capitalize">{user?.role || 'User'}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}